module pc (
    input wire clk,
    input wire reset,
    input wire PCWrite,                     //o/p signal,which will be generated by the hazard_detection_unit(stall) 
    input wire [31:0] pc_next,
    output reg [31:0] pc
);

always @(posedge clk or posedge reset) begin
    if (reset)
        pc <= 32'b0;
    else if (PCWrite)
        pc <= pc_next;
    else
        pc <= pc;
end
endmodule